version: "3"

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      #  - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
